<?php
echo "Add Product";
?>
<form method="post" action="/checkout/cart/add" id="form">
    <label>
        <input type="text" name="form_key" id="form_key" hidden>
        <input type="text" name="sku" id="sku" autocomplete="on">
    </label>
    <button type="submit" title="Add to Cart" class="action tocart primary" name="product_sku" id="button">
        <span>
            Add To Cart
        </span>
    </button>
    <div class="selectList">
    </div>
    <div class="skuProduct">
    </div>
</form>
