<?php
echo "Add Product";
?>

<form method="post" action="/checkout/cart/add" id="form">
    <label>
        <input type="text" name="form_key" id="form_key" hidden>
        <input type="text" name="sku" id="sku" autocomplete="on">
    </label>
    <button type="submit" title="Add to Cart" class="action tocart primary" name="product_sku" id="button">
        <span>
            Add To Cart
        </span>
    </button>
    <input type="file" height="200px" width="200px" name="button">
    <div class="selectList">
    </div>
    <div class="skuProduct">
    </div>
    <div id="employee">

    </div>
</form>
<script id="employee-template" type="text/x-magento-template">
    <ul>
        <li>
            sku : <%- data.sku %>
        </li>
        <li>
             Name : <%- data.name %>
        </li>
        <li>
            <img src=" <%- data.img %>" />
        </li>
    </ul>
</script>
